#define SYSCALL_VALUE_SBRK 1
#define SYSCALL_VALUE_BRK 2 
#define SYSCALL_VALUE_KWRITE 3
#define SYSCALL_VALUE_KIOCTL 4 
#define SYSCALL_VALUE_KFCNTL 5 
#define SYSCALL_VALUE_EXIT 6 
#define SYSCALL_VALUE_KREAD 7 
#define SYSCALL_VALUE_STATX 8 
#define SYSCALL_VALUE_OPEN 9 
#define SYSCALL_VALUE_CLOSE 10 
#define SYSCALL_VALUE_SIGPROCMASK 11
#define SYSCALL_VALUE_KLSEEK 12


